### ISSUE TITLE
Failed to compute 3D conformer

### ISSUE THREAD

**Issue by poinco-gogo** [jwohlwend/boltz#27]
Dear developers,

thank you for making this project open source.

I have encountered a "ValueError: Failed to compute 3D conformer for `CCCCCCCCCCCCCCCCCCCCCCCCC(=O)OC[C@H](COC(=O)CCCCCCCCCCCCCCCCC)O`" error when specifying a compound with a long hydrocarbon chain (`CCCCCCCCCCCCCCCCCCCCCCCCC(=O)OC[C@H](COC(=O)CCCCCCCCCCCCCCCCC)O`) as a ligand.

The error seems to occur in compute_3d_conformer() within schema.py. It appears that conf_id = AllChem.EmbedMolecule(mol, options) returns -1, which causes the error.

After searching, I found a potentially relevant page (<a href="https://github.com/rdkit/rdkit/issues/1593" target="_blank" rel="noopener noreferrer">here</a>). I tried the solution mentioned there (setting params.useRandomCoords=True), and this resolved the error - the protein-ligand complex structure is now being output successfully.

Here's the actual modified code:
```
options.clearConfs = False
options.useRandomCoords=True # inserted
conf_id = -1
 ```

I suggest implementing an option specifically for large ligands. We could allow users to enable this parameter (options.useRandomCoords=True) when dealing with large ligand molecules.

Sincerely,

**Comment by gcorso** [comment]
It should be fixed in the commit (will be live on pypi on the next release)! 

I've made it run with random starting coordinates only in case it fails the generation without random starting coordinates and added a warning given that the conformer generated will be quite different and we have not tested this behavior extensively (but from a couple of examples the output looks fine!)

Big thank you for the recommendation!

**Comment by poinco-gogo** [comment]
@gcorso 
Thanks a lot! The latest code (bc6993) is working well.
